/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EntriesIdRouteImport } from './routes/entries.$id'
import { Route as EntriesNewRouteImport } from './routes/entries.new'
import { Route as ApiDownloadApkRouteImport } from './routes/api/download.apk'
import { Route as ApiV1DashboardRouteImport } from './routes/api/v1/dashboard'
import { Route as ApiV1EntriesRouteImport } from './routes/api/v1/entries'
import { Route as ApiV1ExportRouteImport } from './routes/api/v1/export'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1QuoteRouteImport } from './routes/api/v1/quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdRoute = EntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadApkRoute = ApiDownloadApkRouteImport.update({
  id: '/api/download/apk',
  path: '/api/download/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DashboardRoute = ApiV1DashboardRouteImport.update({
  id: '/api/v1/dashboard',
  path: '/api/v1/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntriesRoute = ApiV1EntriesRouteImport.update({
  id: '/api/v1/entries',
  path: '/api/v1/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportRoute = ApiV1ExportRouteImport.update({
  id: '/api/v1/export',
  path: '/api/v1/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1QuoteRoute = ApiV1QuoteRouteImport.update({
  id: '/api/v1/quote',
  path: '/api/v1/quote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
  '/api/download/apk': typeof ApiDownloadApkRoute
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/entries': typeof ApiV1EntriesRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/quote': typeof ApiV1QuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
  '/api/download/apk': typeof ApiDownloadApkRoute
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/entries': typeof ApiV1EntriesRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/quote': typeof ApiV1QuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
  '/api/download/apk': typeof ApiDownloadApkRoute
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/entries': typeof ApiV1EntriesRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/quote': typeof ApiV1QuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/entries/$id'
    | '/entries/new'
    | '/api/download/apk'
    | '/api/v1/dashboard'
    | '/api/v1/entries'
    | '/api/v1/export'
    | '/api/v1/health'
    | '/api/v1/me'
    | '/api/v1/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/entries/$id'
    | '/entries/new'
    | '/api/download/apk'
    | '/api/v1/dashboard'
    | '/api/v1/entries'
    | '/api/v1/export'
    | '/api/v1/health'
    | '/api/v1/me'
    | '/api/v1/quote'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/entries/$id'
    | '/entries/new'
    | '/api/download/apk'
    | '/api/v1/dashboard'
    | '/api/v1/entries'
    | '/api/v1/export'
    | '/api/v1/health'
    | '/api/v1/me'
    | '/api/v1/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  EntriesIdRoute: typeof EntriesIdRoute
  EntriesNewRoute: typeof EntriesNewRoute
  ApiDownloadApkRoute: typeof ApiDownloadApkRoute
  ApiV1DashboardRoute: typeof ApiV1DashboardRoute
  ApiV1EntriesRoute: typeof ApiV1EntriesRoute
  ApiV1ExportRoute: typeof ApiV1ExportRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1QuoteRoute: typeof ApiV1QuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/apk': {
      id: '/api/download/apk'
      path: '/api/download/apk'
      fullPath: '/api/download/apk'
      preLoaderRoute: typeof ApiDownloadApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dashboard': {
      id: '/api/v1/dashboard'
      path: '/api/v1/dashboard'
      fullPath: '/api/v1/dashboard'
      preLoaderRoute: typeof ApiV1DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/entries': {
      id: '/api/v1/entries'
      path: '/api/v1/entries'
      fullPath: '/api/v1/entries'
      preLoaderRoute: typeof ApiV1EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export': {
      id: '/api/v1/export'
      path: '/api/v1/export'
      fullPath: '/api/v1/export'
      preLoaderRoute: typeof ApiV1ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/quote': {
      id: '/api/v1/quote'
      path: '/api/v1/quote'
      fullPath: '/api/v1/quote'
      preLoaderRoute: typeof ApiV1QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  EntriesIdRoute: EntriesIdRoute,
  EntriesNewRoute: EntriesNewRoute,
  ApiDownloadApkRoute: ApiDownloadApkRoute,
  ApiV1DashboardRoute: ApiV1DashboardRoute,
  ApiV1EntriesRoute: ApiV1EntriesRoute,
  ApiV1ExportRoute: ApiV1ExportRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1QuoteRoute: ApiV1QuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
